services:
  - type: web
    name: driver-service
    env: java
    buildCommand: ./mvnw clean install -DskipTests
    startCommand: java -jar target/*.jar
    dockerfilePath: ./Dockerfile
    envVars:
      - key: MYSQL_DRIVER_DB_URL
        value: jdbc:mysql://mysql.railway.internal:3306/railway
      - key: MYSQL_DRIVER_USERNAME
        value: root
      - key: MYSQL_DRIVER_PASSWORD
        value: GJhVbkjBonzsXUtSyBPqMqYziUDEVVSs
      - key: REDIS_HOST
        value: maximum-gnat-13969.upstash.io
      - key: REDIS_PORT
        value: 6379
      - key: REDIS_TIMEOUT
        value: 5000
      - key: JWT_SECRET_DRIVER
        value: dhurrah-secret-key-that-is-at-least-64-characters-long-dhurrah123456789
      - key: EUREKA_SERVER_ADDRESS
        value: https://apigateway-twdm.onrender.com/eureka
