server:
  port: 8080

spring:
  application:
    name: API_GATEWAY
  cloud:
    gateway:
      websocket:
        enabled: true
      routes:
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user/**

        - id: driver-service
          uri: lb://DRIVER-SERVICE
          predicates:
            - Path=/driver/**

        - id: ride-service
          uri: lb://RIDE-SERVICE
          predicates:
            - Path=/ride/**

        - id: location-service
          uri: lb://LOCATION-SERVICE
          predicates:
            - Path=/location/**



      default-filters:
        - AddResponseHeader=X-Gateway-Filter, Applied

      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - ${FRONT_END_1_URL}
              - ${FRONT_END_2_URL}
              - ${FRONT_END_APP_URL}
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders:
              - "*"
            allowCredentials: true
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_URL}
management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

jwt:
  secret:
    key: ${JWT_SECRET_KEY}
