services:
  - type: web
    name: discovery-server
    env: java
    buildCommand: |
      curl -s "https://download.oracle.com/java/21/latest/jdk-21_linux-x64_bin.tar.gz" | tar xz
      mv jdk-21* java21
      export JAVA_HOME=$PWD/java21
      export PATH=$JAVA_HOME/bin:$PATH
      ./mvnw clean install
    startCommand: java -jar target/Eureka-0.0.1-SNAPSHOT.jar
    envVars:
      - key: JAVA_HOME
        value: /opt/render/project/java21
      - key: PATH
        value: /opt/render/project/java21/bin:$PATH
