server:
  port: 1214

spring:
  application:
    name: RIDE-SERVICE

  datasource:
    url: ${POSTGRES_URL}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  redis:
    host: ${REDIS_HOST}
    port: ${REDIS_PORT}
    timeout: ${REDIS_TIMEOUT}

  cache:
    type: redis

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_ADDRESS}
    register-with-eureka: true
    fetch-registry: true

api-gateway:
  url: ${API_GATEWAY_URL}

logging:
  level:
    root: INFO
    org.hibernate.SQL: DEBUG
