server:
  port: 1214

spring:
  application:
    name: RIDE-SERVICE

  datasource:
    url: ${POSTGRES_URL}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  redis:
    url: ${SPRING_DATA_REDIS_URL}
    timeout: ${SPRING_DATA_REDIS_TIMEOUT}
  cache:
    type: redis




weather:
  key: ${WEATHER_APIKEY}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_ADDRESS}
    register-with-eureka: true
    fetch-registry: true

  instance:
    prefer-ip-address: true
    hostname: localhost   # ✅ This avoids .mshome.net issues

api-gateway:
  url: ${API_GATEWAY_URL}

ors:
  api:
    key: ${ORS_API_KEY}

logging:
  level:
    root: INFO
    org.hibernate.SQL: DEBUG
